version: "3.9"
services:
  fluentbit:
    image: fluent/fluent-bit:2.1.10
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./scripts/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./scripts/fluentbit/map.json:/fluent-bit/etc/map.json
      - ./scripts/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./logs:/app/logs

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/demo-dashboards
      - grafana_data:/var/lib/grafana

  my-postgres:
    image: postgres
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: db_course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    logging:
      driver: fluentd
      options:
        tag: postgres
        fluentd-sub-second-precision: "true"
    volumes:
      - postgres:/var/lib/postgresql/data/

  my-redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/bitnami
    ports:
      - "6379:6379"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./scripts/loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./scripts/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=5m"
      - "--storage.tsdb.retention.size=10GB"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  grafana_data:
  postgres:
  redis_data:
  prometheus_data:
